// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Log.proto

package cn.edu.buaa.act.hybridcloud.gossip.proto;

public final class LogProtos {
  private LogProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Log)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string memberID = 1;</code>
     */
    String getMemberID();
    /**
     * <code>optional string memberID = 1;</code>
     */
    com.google.protobuf.ByteString
        getMemberIDBytes();

    /**
     * <code>optional uint64 TSM = 2;</code>
     */
    long getTSM();

    /**
     * <code>optional uint64 TOSN = 3;</code>
     */
    long getTOSN();

    /**
     * <code>repeated string received = 4;</code>
     */
    java.util.List<String>
        getReceivedList();
    /**
     * <code>repeated string received = 4;</code>
     */
    int getReceivedCount();
    /**
     * <code>repeated string received = 4;</code>
     */
    String getReceived(int index);
    /**
     * <code>repeated string received = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceivedBytes(int index);

    /**
     * <code>optional .proto.Request update = 5;</code>
     */
    boolean hasUpdate();
    /**
     * <code>optional .proto.Request update = 5;</code>
     */
    RequestProtos.Request getUpdate();
    /**
     * <code>optional .proto.Request update = 5;</code>
     */
    RequestProtos.RequestOrBuilder getUpdateOrBuilder();

    /**
     * <code>optional string date = 6;</code>
     */
    String getDate();
    /**
     * <code>optional string date = 6;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code proto.Log}
   */
  public  static final class Log extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Log)
      LogOrBuilder {
    // Use Log.newBuilder() to construct.
    private Log(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Log() {
      memberID_ = "";
      tSM_ = 0L;
      tOSN_ = 0L;
      received_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      date_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Log(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              memberID_ = s;
              break;
            }
            case 16: {

              tSM_ = input.readUInt64();
              break;
            }
            case 24: {

              tOSN_ = input.readUInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                received_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              received_.add(s);
              break;
            }
            case 42: {
              RequestProtos.Request.Builder subBuilder = null;
              if (update_ != null) {
                subBuilder = update_.toBuilder();
              }
              update_ = input.readMessage(RequestProtos.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(update_);
                update_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          received_ = received_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogProtos.internal_static_proto_Log_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogProtos.internal_static_proto_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Log.class, Builder.class);
    }

    private int bitField0_;
    public static final int MEMBERID_FIELD_NUMBER = 1;
    private volatile Object memberID_;
    /**
     * <code>optional string memberID = 1;</code>
     */
    public String getMemberID() {
      Object ref = memberID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        memberID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string memberID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIDBytes() {
      Object ref = memberID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        memberID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TSM_FIELD_NUMBER = 2;
    private long tSM_;
    /**
     * <code>optional uint64 TSM = 2;</code>
     */
    public long getTSM() {
      return tSM_;
    }

    public static final int TOSN_FIELD_NUMBER = 3;
    private long tOSN_;
    /**
     * <code>optional uint64 TOSN = 3;</code>
     */
    public long getTOSN() {
      return tOSN_;
    }

    public static final int RECEIVED_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList received_;
    /**
     * <code>repeated string received = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReceivedList() {
      return received_;
    }
    /**
     * <code>repeated string received = 4;</code>
     */
    public int getReceivedCount() {
      return received_.size();
    }
    /**
     * <code>repeated string received = 4;</code>
     */
    public String getReceived(int index) {
      return received_.get(index);
    }
    /**
     * <code>repeated string received = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceivedBytes(int index) {
      return received_.getByteString(index);
    }

    public static final int UPDATE_FIELD_NUMBER = 5;
    private RequestProtos.Request update_;
    /**
     * <code>optional .proto.Request update = 5;</code>
     */
    public boolean hasUpdate() {
      return update_ != null;
    }
    /**
     * <code>optional .proto.Request update = 5;</code>
     */
    public RequestProtos.Request getUpdate() {
      return update_ == null ? RequestProtos.Request.getDefaultInstance() : update_;
    }
    /**
     * <code>optional .proto.Request update = 5;</code>
     */
    public RequestProtos.RequestOrBuilder getUpdateOrBuilder() {
      return getUpdate();
    }

    public static final int DATE_FIELD_NUMBER = 6;
    private volatile Object date_;
    /**
     * <code>optional string date = 6;</code>
     */
    public String getDate() {
      Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>optional string date = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMemberIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, memberID_);
      }
      if (tSM_ != 0L) {
        output.writeUInt64(2, tSM_);
      }
      if (tOSN_ != 0L) {
        output.writeUInt64(3, tOSN_);
      }
      for (int i = 0; i < received_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, received_.getRaw(i));
      }
      if (update_ != null) {
        output.writeMessage(5, getUpdate());
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, date_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMemberIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, memberID_);
      }
      if (tSM_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, tSM_);
      }
      if (tOSN_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, tOSN_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < received_.size(); i++) {
          dataSize += computeStringSizeNoTag(received_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getReceivedList().size();
      }
      if (update_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUpdate());
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, date_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Log)) {
        return super.equals(obj);
      }
      Log other = (Log) obj;

      boolean result = true;
      result = result && getMemberID()
          .equals(other.getMemberID());
      result = result && (getTSM()
          == other.getTSM());
      result = result && (getTOSN()
          == other.getTOSN());
      result = result && getReceivedList()
          .equals(other.getReceivedList());
      result = result && (hasUpdate() == other.hasUpdate());
      if (hasUpdate()) {
        result = result && getUpdate()
            .equals(other.getUpdate());
      }
      result = result && getDate()
          .equals(other.getDate());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
      hash = (53 * hash) + getMemberID().hashCode();
      hash = (37 * hash) + TSM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTSM());
      hash = (37 * hash) + TOSN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTOSN());
      if (getReceivedCount() > 0) {
        hash = (37 * hash) + RECEIVED_FIELD_NUMBER;
        hash = (53 * hash) + getReceivedList().hashCode();
      }
      if (hasUpdate()) {
        hash = (37 * hash) + UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdate().hashCode();
      }
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Log prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Log}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Log)
        LogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogProtos.internal_static_proto_Log_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogProtos.internal_static_proto_Log_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Log.class, Builder.class);
      }

      // Construct using LogProtos.Log.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        memberID_ = "";

        tSM_ = 0L;

        tOSN_ = 0L;

        received_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (updateBuilder_ == null) {
          update_ = null;
        } else {
          update_ = null;
          updateBuilder_ = null;
        }
        date_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogProtos.internal_static_proto_Log_descriptor;
      }

      public Log getDefaultInstanceForType() {
        return Log.getDefaultInstance();
      }

      public Log build() {
        Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Log buildPartial() {
        Log result = new Log(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.memberID_ = memberID_;
        result.tSM_ = tSM_;
        result.tOSN_ = tOSN_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          received_ = received_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.received_ = received_;
        if (updateBuilder_ == null) {
          result.update_ = update_;
        } else {
          result.update_ = updateBuilder_.build();
        }
        result.date_ = date_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Log) {
          return mergeFrom((Log)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Log other) {
        if (other == Log.getDefaultInstance()) return this;
        if (!other.getMemberID().isEmpty()) {
          memberID_ = other.memberID_;
          onChanged();
        }
        if (other.getTSM() != 0L) {
          setTSM(other.getTSM());
        }
        if (other.getTOSN() != 0L) {
          setTOSN(other.getTOSN());
        }
        if (!other.received_.isEmpty()) {
          if (received_.isEmpty()) {
            received_ = other.received_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureReceivedIsMutable();
            received_.addAll(other.received_);
          }
          onChanged();
        }
        if (other.hasUpdate()) {
          mergeUpdate(other.getUpdate());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Log parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Log) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object memberID_ = "";
      /**
       * <code>optional string memberID = 1;</code>
       */
      public String getMemberID() {
        Object ref = memberID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          memberID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string memberID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIDBytes() {
        Object ref = memberID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          memberID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string memberID = 1;</code>
       */
      public Builder setMemberID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memberID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string memberID = 1;</code>
       */
      public Builder clearMemberID() {
        
        memberID_ = getDefaultInstance().getMemberID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string memberID = 1;</code>
       */
      public Builder setMemberIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memberID_ = value;
        onChanged();
        return this;
      }

      private long tSM_ ;
      /**
       * <code>optional uint64 TSM = 2;</code>
       */
      public long getTSM() {
        return tSM_;
      }
      /**
       * <code>optional uint64 TSM = 2;</code>
       */
      public Builder setTSM(long value) {
        
        tSM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 TSM = 2;</code>
       */
      public Builder clearTSM() {
        
        tSM_ = 0L;
        onChanged();
        return this;
      }

      private long tOSN_ ;
      /**
       * <code>optional uint64 TOSN = 3;</code>
       */
      public long getTOSN() {
        return tOSN_;
      }
      /**
       * <code>optional uint64 TOSN = 3;</code>
       */
      public Builder setTOSN(long value) {
        
        tOSN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 TOSN = 3;</code>
       */
      public Builder clearTOSN() {
        
        tOSN_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList received_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReceivedIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          received_ = new com.google.protobuf.LazyStringArrayList(received_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getReceivedList() {
        return received_.getUnmodifiableView();
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public int getReceivedCount() {
        return received_.size();
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public String getReceived(int index) {
        return received_.get(index);
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceivedBytes(int index) {
        return received_.getByteString(index);
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public Builder setReceived(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceivedIsMutable();
        received_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public Builder addReceived(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceivedIsMutable();
        received_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public Builder addAllReceived(
          Iterable<String> values) {
        ensureReceivedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, received_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public Builder clearReceived() {
        received_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string received = 4;</code>
       */
      public Builder addReceivedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureReceivedIsMutable();
        received_.add(value);
        onChanged();
        return this;
      }

      private RequestProtos.Request update_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          RequestProtos.Request, RequestProtos.Request.Builder, RequestProtos.RequestOrBuilder> updateBuilder_;
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public boolean hasUpdate() {
        return updateBuilder_ != null || update_ != null;
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public RequestProtos.Request getUpdate() {
        if (updateBuilder_ == null) {
          return update_ == null ? RequestProtos.Request.getDefaultInstance() : update_;
        } else {
          return updateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public Builder setUpdate(RequestProtos.Request value) {
        if (updateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          update_ = value;
          onChanged();
        } else {
          updateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public Builder setUpdate(
          RequestProtos.Request.Builder builderForValue) {
        if (updateBuilder_ == null) {
          update_ = builderForValue.build();
          onChanged();
        } else {
          updateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public Builder mergeUpdate(RequestProtos.Request value) {
        if (updateBuilder_ == null) {
          if (update_ != null) {
            update_ =
              RequestProtos.Request.newBuilder(update_).mergeFrom(value).buildPartial();
          } else {
            update_ = value;
          }
          onChanged();
        } else {
          updateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public Builder clearUpdate() {
        if (updateBuilder_ == null) {
          update_ = null;
          onChanged();
        } else {
          update_ = null;
          updateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public RequestProtos.Request.Builder getUpdateBuilder() {
        
        onChanged();
        return getUpdateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      public RequestProtos.RequestOrBuilder getUpdateOrBuilder() {
        if (updateBuilder_ != null) {
          return updateBuilder_.getMessageOrBuilder();
        } else {
          return update_ == null ?
              RequestProtos.Request.getDefaultInstance() : update_;
        }
      }
      /**
       * <code>optional .proto.Request update = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RequestProtos.Request, RequestProtos.Request.Builder, RequestProtos.RequestOrBuilder>
          getUpdateFieldBuilder() {
        if (updateBuilder_ == null) {
          updateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RequestProtos.Request, RequestProtos.Request.Builder, RequestProtos.RequestOrBuilder>(
                  getUpdate(),
                  getParentForChildren(),
                  isClean());
          update_ = null;
        }
        return updateBuilder_;
      }

      private Object date_ = "";
      /**
       * <code>optional string date = 6;</code>
       */
      public String getDate() {
        Object ref = date_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public Builder setDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Log)
    }

    // @@protoc_insertion_point(class_scope:proto.Log)
    private static final Log DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Log();
    }

    public static Log getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Log>
        PARSER = new com.google.protobuf.AbstractParser<Log>() {
      public Log parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Log(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Log> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Log> getParserForType() {
      return PARSER;
    }

    public Log getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Log_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Log_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tLog.proto\022\005proto\032\rRequest.proto\"r\n\003Log" +
      "\022\020\n\010memberID\030\001 \001(\t\022\013\n\003TSM\030\002 \001(\004\022\014\n\004TOSN\030" +
      "\003 \001(\004\022\020\n\010received\030\004 \003(\t\022\036\n\006update\030\005 \001(\0132" +
      "\016.proto.Request\022\014\n\004date\030\006 \001(\tB)\n\034com.don" +
      "gjinyong.gossip.protoB\tLogProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RequestProtos.getDescriptor(),
        }, assigner);
    internal_static_proto_Log_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Log_descriptor,
        new String[] { "MemberID", "TSM", "TOSN", "Received", "Update", "Date", });
    RequestProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
